version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=Students
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8002"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/Students?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network